README.md
bin/iop
istio-control/istio-config/templates/deployment.yaml
istio-control/istio-discovery/values.yaml
security/citadel/values.yaml

Please have a look at the issues we faced during using the istio-installer.

Adapt istio-installer after testing

---

README.md

Document findings after trying out.

Adapt documentation

---

.concourse/Dockerfile
.concourse/concourse.yaml
.concourse/set-pipeline.sh

Co-authored-by: Axel Siebenborn <axel.siebenborn@sap.com>

Add concourse install pipeline

---

security/citadel/values.yaml

Co-authored-by: Axel Siebenborn <axel.siebenborn@sap.com>
Signed-off-by: Julia Plachetka <julia.plachetka@sap.com>

Add istio-control-master to namespaces to be considered by citadel.

---

global.yaml
istio-control/istio-config/templates/deployment.yaml

The version is needed to provide the correct flags to galley.
Co-authored-by: Axel Siebenborn <axel.siebenborn@sap.com>
Signed-off-by: Julia Plachetka <julia.plachetka@sap.com>

Add istio-version to globals.yaml.

---

.concourse/concourse.yaml
bin/test.sh

Fix concourse install pipeline

---

.circleci/config.yml
bin/install.sh
bin/test.sh
bin/testEnvRootMinikube.sh

Installs using modular installer and test installation with bookinfo. See https://github.com/istio-ecosystem/istio-installer/issues/5#issuecomment-475533635

Circleci modular

---

.circleci/config.yml
.mergify.yml
Makefile
bin/install.sh
bin/iop
bin/test.sh
gateways/istio-ingress/templates/service.yaml
istio-control/istio-discovery/values.yaml
test/docker/Dockerfile
test/kind/user-values.yaml

More CI/CD automation

---

security/citadel/templates/deployment.yaml
security/citadel/values.yaml

This PR is for the issue: https://github.com/istio/istio/issues/13383. The counterpart of this PR on istio/istio repo is at https://github.com/istio/istio/pull/13519.

Only allow one replica of Citadel

---

.concourse/concourse.yaml
bin/install.sh
bin/test.sh

As mtls was disabled in PR #42

don't use mtls for bookinfo destination rules in test.sh

---

CONTRIBUTING.md

This is a copy of $ISTIO/istio/CONTRIBUTING.md with some modifications
tailoreed towards the installer.

Add a link to the istio/community guidelines

---

Makefile

fix issue#61 for existing files

Add -p flag for mkdir to fix build issue

---

README.md

Signed-off-by: Philipp Stehle <philipp.stehle@sap.com>

Update CircleCI badge to new repo url

---

.circleci/config.yml
.concourse/concourse.yaml
Makefile
test/noauth.mk

Since we have transferred the new installer to Istio org, we need to update the import path to reflect that change.

update import path.

---

Makefile

to use true on already configured path to avoid errors like not able to find /bin/true on MacOS.

minor update to makefile

---

.mergify.yml

The circle rules need to match the title of the test. Also added some
extra stuff we are using in docs repo, to prevent accidental merges.

Fix mergify rules

---

global.yaml
istio-control/istio-autoinject/files/injection-template.yaml
istio-control/istio-autoinject/templates/deployment.yaml
istio-control/istio-autoinject/templates/mutatingwebhook.yaml
istio-control/istio-autoinject/values.yaml

Signed-off-by: John Howard <howardjohn@google.com>

Sync sidecar injector with master

---

test/install.mk
test/noauth.mk

Metrics were not being recorded because we don't pass all of the
relevant namespaces.
This will be a little cleaner when we have https://github.com/istio/installer/pull/83
Fixes https://github.com/istio/installer/issues/89

Fix prometheus metrics

---

Makefile
test/buildkite/Dockerfile
test/docker/Dockerfile

- Docker image creation
- tests

First pass at getting things to work on a Mac

---

.circleci/config.yml

Before it used the install.sh script which won't work for the tests
currently

Fix minikube

---

istio-control/istio-config/templates/_podDisruptionBudget.tpl
istio-control/istio-config/templates/clusterrole.yaml
istio-control/istio-config/templates/clusterrolebinding.yaml
istio-control/istio-config/templates/configmap-envoy.yaml
istio-control/istio-config/templates/deployment.yaml
istio-control/istio-config/templates/poddisruptionbudget.yaml
istio-control/istio-config/templates/service.yaml
istio-control/istio-config/templates/validatingwebhookconfiguration.yaml.tpl
istio-control/istio-config/values.yaml

Signed-off-by: John Howard <howardjohn@google.com>

Sync galley templates with master

---

test/tests.mk

Pass namespace to integ tests

---

global.yaml
istio-control/istio-config/templates/_podDisruptionBudget.tpl
istio-control/istio-config/templates/deployment.yaml
istio-control/istio-config/templates/poddisruptionbudget.yaml
istio-control/istio-config/templates/service.yaml

I fixed this issues in my pr to sync galley to master, but accidentally overrode them later, so they got missed.

Fix overridden galley fixes

---

.circleci/config.yml
Makefile
istio-control/istio-discovery/templates/configmap-envoy.yaml
istio-telemetry/grafana/templates/deployment.yaml
istio-telemetry/mixer-telemetry/templates/configmap-envoy.yaml
istio-telemetry/mixer-telemetry/templates/deployment.yaml
istio-telemetry/prometheus/values.yaml
kustomize/istio-ingress/istio-ingress.yaml
kustomize/istio-telemetry/kustomization.yaml
test/demo.mk
test/demo/istio-testing/k8s.yaml
test/demo/k8s.yaml
test/demo/mesh.yaml
test/demo/values.yaml
test/docker/Dockerfile
test/install.mk
test/tests.mk

Also updates artifacts ( make build ) - we'll need to automate this soon.

Move telemetry to MCP connection to use sidecar, like pilot.

---

Makefile
test/docker/Dockerfile

Fixes https://github.com/istio/installer/issues/117

Build istioctl during image creation

---

gateways/istio-ingress/values.yaml

Fix: https://github.com/istio/installer/issues/124

fix probe issue for ingress gateway.

---

test/demo/k8s.yaml
test/demo/values.yaml
test/install.mk

Hopefully fix https://github.com/istio/installer/issues/125
Most of changes are from updating the demo yaml, the real change is the values.yaml

Use demo values for demo

---

istio-control/istio-autoinject/templates/poddisruptionbudget.yaml

Resolve: https://github.com/istio/installer/issues/133

add pdb for sidecar_injector.

---

gateways/istio-egress/values.yaml
gateways/istio-ingress/values.yaml
istio-control/istio-autoinject/values.yaml
istio-control/istio-config/values.yaml
istio-control/istio-discovery/values.yaml
istio-policy/values.yaml
istio-telemetry/grafana/values.yaml
istio-telemetry/mixer-telemetry/values.yaml
istio-telemetry/prometheus/values.yaml
security/citadel/values.yaml
test/demo/istio-testing/k8s.yaml
test/demo/k8s.yaml

Merge fix of https://github.com/istio/istio/pull/13905 to new installer.

fix type issue of pod antiaffinity.

---

istiocoredns/Chart.yaml
istiocoredns/templates/_affinity.tpl
istiocoredns/templates/clusterrole.yaml
istiocoredns/templates/clusterrolebinding.yaml
istiocoredns/templates/configmap.yaml
istiocoredns/templates/deployment.yaml
istiocoredns/templates/service.yaml
istiocoredns/templates/serviceaccount.yaml
istiocoredns/values.yaml

import istiocoredns chart.

---

security/nodeagent/Chart.yaml
security/nodeagent/templates/_affinity.tpl
security/nodeagent/templates/clusterrole.yaml
security/nodeagent/templates/clusterrolebinding.yaml
security/nodeagent/templates/daemonset.yaml
security/nodeagent/templates/serviceaccount.yaml
security/nodeagent/values.yaml

import nodeagent chart.

---

kustomize/citadel/citadel.yaml
kustomize/istio-ingress/istio-ingress.yaml
test/demo/istio-testing/k8s.yaml
test/demo/k8s.yaml

This just updates the generated files

Run make build

---

.circleci/config.yml
test/knative/service.yaml
test/knative/serving.yaml
test/noauth.mk

knative serving is taken from
https://github.com/knative/serving/releases/download/v0.5.2/serving.yaml

Add test which installs a minimal istio to get knative serving running.

---

global.yaml
istio-control/istio-autoinject/files/injection-template.yaml

backport https://github.com/istio/istio/pull/13970
cc @jroper

Support excludeOutboundPorts

---

gateways/istio-egress/templates/deployment.yaml
gateways/istio-egress/templates/service.yaml
gateways/istio-ingress/templates/deployment.yaml
test/demo.mk
test/install.mk
test/noauth.mk

These should match what we have in master and be consistent with other
components.

Fix gateway names

---

istio-telemetry/grafana/dashboards/istio-performance-dashboard.json
istio-telemetry/grafana/dashboards/mixer-dashboard.json

This PR adopts the work in https://github.com/istio/istio/pull/10934 and corrects some of Mixer Pilot confusion introduced in earlier PRs.

fix(dashboards): resolve a few minor issues around job names and queries

---

global.yaml
istio-control/istio-discovery/templates/deployment.yaml
istio-control/istio-discovery/values.yaml

Context: support watching multiple namespaces for pilot
This is a followup PR for https://github.com/istio/istio/pull/13635

support multiple app namespaces.

---

Makefile
bin/install.sh
gateways/istio-ingress/templates/addongateway.yaml
gateways/istio-ingress/templates/certificate.yaml
gateways/istio-ingress/values.yaml
global.yaml
istio-telemetry/kiali/Chart.yaml
istio-telemetry/kiali/templates/_affinity.tpl
istio-telemetry/kiali/templates/clusterrole.yaml
istio-telemetry/kiali/templates/clusterrolebinding.yaml
istio-telemetry/kiali/templates/configmap.yaml
istio-telemetry/kiali/templates/demosecret.yaml
istio-telemetry/kiali/templates/deployment.yaml
istio-telemetry/kiali/templates/service.yaml
istio-telemetry/kiali/templates/serviceaccount.yaml
istio-telemetry/kiali/values.yaml
test/install.mk

Import kiali templates from master and update
Update telemetry installation with grafana and kiali

Import kiali templates

---

.circleci/config.yml
Makefile
test/demo.mk
test/install.mk
test/noauth.mk
test/tests.mk

Resolve: #82
Context: https://github.com/istio/installer/pull/83

Isolate components in different namespaces.

---

gateways/istio-ingress/templates/addongateway.yaml
gateways/istio-ingress/templates/certificate.yaml
gateways/istio-ingress/values.yaml
istio-telemetry/tracing/Chart.yaml
istio-telemetry/tracing/templates/_affinity.tpl
istio-telemetry/tracing/templates/deployment-jaeger.yaml
istio-telemetry/tracing/templates/deployment-zipkin.yaml
istio-telemetry/tracing/templates/service-jaeger.yaml
istio-telemetry/tracing/templates/service.yaml
istio-telemetry/tracing/values.yaml
test/install.mk

Import tracing related templates

---

.circleci/config.yml
test/install.mk
test/tests.mk

Adds a new job to circleci, which does the following:
- installs minimal istio
- runs the echo integration test

Echo-test for minimal installation in CI.

---

kustomize/istio-telemetry/mixer-telemetry.yaml

telemetry is broken due to this.

fix configNamespace for telemetry

---

istio-telemetry/prometheus-operator/templates/servicemonitors.yaml

resolves https://github.com/istio/istio/issues/14164

Add cadvisor service monitor, http only

---

istio-telemetry/kiali/templates/_affinity.tpl
istio-telemetry/kiali/values.yaml
istio-telemetry/tracing/templates/_affinity.tpl
istio-telemetry/tracing/values.yaml
security/certmanager/values.yaml

Merge the fix https://github.com/istio/installer/pull/157 to the charts imported later.

fix pod anti affinity for the charts imported later.

---

security/certmanager/templates/deployment.yaml
security/certmanager/values.yaml

This fixes: https://github.com/istio/istio/issues/14380

Make number of certmanager replicas configurable

---

istio-control/istio-discovery/templates/configmap.yaml
istio-control/istio-discovery/values.yaml
istio-telemetry/mixer-telemetry/values.yaml

Synchronize https://github.com/istio/istio/pull/14301 to this repo

added batch reporting parameters as helm variables

---

bin/install.sh

Use correct deployment name for `kubectl patch`.
Co-authored-by: Ulrich Kramer <u.kramer@sap.com>

Fix concourse pipeline (istio-ingressgateway naming).

---

gateways/istio-egress/templates/deployment.yaml
gateways/istio-ingress/templates/deployment.yaml
istio-control/istio-autoinject/files/injection-template.yaml
istio-control/istio-discovery/templates/deployment.yaml
istio-policy/templates/deployment.yaml
istio-telemetry/mixer-telemetry/templates/deployment.yaml
kustomize/istio-control/istio-autoinject.yaml
kustomize/istio-telemetry/istio-grafana.yaml
test/demo/k8s.yaml

cherrypick https://github.com/istio/istio/pull/14855 into installer

mount directory instead of file to detect file change

---

security/nodeagent/templates/daemonset.yaml

cherrypick https://github.com/istio/istio/pull/15079 to installer

cherrypick #15079 to installer 

---

README.md

I'm not sure this is equivalent (especially for security, was the original intention to install only citadel, or more?). But at least it works.
Also clarify what IBASE is and (accidentally, really) strip leading whitespace.

Fix sample instructions for security and gateways

---

security/citadel/templates/deployment.yaml
security/citadel/templates/poddisruptionbudget.yaml
security/citadel/values.yaml

- merge https://github.com/istio/istio/pull/14961 to enable multiple citadel instances support
- enable pdb for citadel since we have multiple instances support

multiple instances support and pdb enabled for citadel.

---

README.md

Fixes https://github.com/istio/istio/issues/15165

Fix sidecarInjectorWebhook.enableNamespacesByDefault in README

---

security/nodeagent/templates/daemonset.yaml

cherrypick change in https://github.com/istio/istio/pull/15199 to installer

cherrypick removing hardcoded istio-system

---

README.md

This is a general cleanup of the readme. Fixes:
* Small grammatical errors
* Lots of adding backticks because my eyes hurt otherwise
* Some sections were unclear, particularly the bits around how the
'environment' name is determined
* Some sections weren't really 'noob friendly' eg. the references to
'kube-inject' instead of `istioctl kube-inject`

General readme cleanup

---

gateways/istio-ingress/values.yaml

There is already one exists at line 9

Remove extra sds entry

---

kustomize/micro/allocation.yaml
security/citadel/templates/deployment.yaml
test/k8s/etcd.yaml
test/k8s/loadgen.yaml

https://github.com/istio/istio/issues/12211
These are removed in k8s 1.16

Migrate to apps/v1

---

gateways/istio-egress/templates/deployment.yaml
gateways/istio-ingress/templates/deployment.yaml
istio-control/istio-autoinject/files/injection-template.yaml
istio-control/istio-autoinject/templates/deployment.yaml
istio-control/istio-config/templates/deployment.yaml
istio-control/istio-discovery/templates/deployment.yaml
istio-policy/templates/deployment.yaml
istio-telemetry/grafana/templates/deployment.yaml
istio-telemetry/kiali/templates/deployment.yaml
istio-telemetry/mixer-telemetry/templates/deployment.yaml
istio-telemetry/prometheus/templates/deployment.yaml
istio-telemetry/tracing/templates/deployment-jaeger.yaml
istio-telemetry/tracing/templates/deployment-zipkin.yaml
istiocoredns/templates/deployment.yaml
security/certmanager/templates/deployment.yaml
security/citadel/templates/deployment.yaml
security/nodeagent/templates/daemonset.yaml

Use global imagePullPolicy

---

test/install.mk

Previous there was still a race where one CRD would be ready but others
were not

Wait for all prometheus operator CRDs

---

.circleci/config.yml
Makefile
test/docker/Dockerfile

I will move to a real istio repo if this passes tests ok, adding hold for now

Update builder to kind v0.4.0

---

istio-control/istio-autoinject/files/injection-template.yaml
istio-control/istio-autoinject/templates/deployment.yaml
kustomize/istio-1.2/default/kustomization.yaml
security/citadel/templates/deployment.yaml
security/citadel/templates/service.yaml

Small fixes and updates from master.

---

crds/files/crd-10.yaml
crds/files/crd-11.yaml
crds/files/crd-12.yaml
crds/files/crd-certmanager-10.yaml
crds/files/crd-certmanager-11.yaml

Please refer to https://github.com/istio/istio/pull/15615

Update versions field in crds definition.

---

istio-telemetry/kiali/Chart.yaml
istio-telemetry/kiali/templates/configmap.yaml
istio-telemetry/kiali/templates/deployment.yaml
istio-telemetry/kiali/values.yaml

refer to this pr - https://github.com/istio/istio/pull/15372

Upgrade kaili to v1.1.0

---

istio-control/istio-config/templates/configmap.yaml
istio-control/istio-config/templates/validatingwebhookconfiguration.yaml.tpl

align with https://github.com/istio/istio/pull/10651

Delete validatingwebhookconfiguration if configValidation=false

---

istio-telemetry/kiali/templates/clusterrolebinding.yaml

merged the pr - https://github.com/istio/istio/pull/15690

fix istio upgrade issue

---

istio-control/istio-discovery/templates/enable-mesh-mtls.yaml
kustomize/istio-control/discovery/discovery.yaml
kustomize/micro/discovery.yaml
test/demo/k8s.yaml

remove namespace for cluster scoped resource: `MeshPolicy`.

remove namespace for meshpolicy.

---

istio-control/istio-autoinject/templates/deployment.yaml
istio-control/istio-autoinject/templates/service.yaml
istio-control/istio-config/templates/deployment.yaml
istio-control/istio-config/templates/service.yaml
kustomize/istio-1.2/default/istio.yaml
kustomize/istio-control/istio-config.yaml
test/demo/k8s.yaml

Resolve the leftover issue for nonroot user to run container. refer to https://github.com/istio/istio/issues/15984

Change to fit for container run as nonrun

---

istio-telemetry/tracing/templates/deployment-jaeger.yaml
istio-telemetry/tracing/templates/pvc.yaml
istio-telemetry/tracing/values.yaml

align with https://github.com/istio/istio/pull/16010

Jaeger to support badger

---

gateways/istio-egress/templates/deployment.yaml
gateways/istio-egress/values.yaml
gateways/istio-ingress/templates/deployment.yaml
gateways/istio-ingress/values.yaml
istio-control/istio-autoinject/templates/deployment.yaml
istio-control/istio-autoinject/values.yaml
istio-control/istio-config/templates/deployment.yaml
istio-control/istio-config/values.yaml
istio-control/istio-discovery/templates/deployment.yaml
istio-control/istio-discovery/values.yaml
istio-policy/templates/deployment.yaml
istio-policy/values.yaml
istio-telemetry/mixer-telemetry/templates/deployment.yaml
istio-telemetry/mixer-telemetry/values.yaml
istiocoredns/templates/deployment.yaml
istiocoredns/values.yaml
security/citadel/templates/deployment.yaml
security/citadel/values.yaml

Context: https://github.com/istio/istio/issues/13552 & https://github.com/istio/istio/issues/15878

add configurable rolling update strategy.

---

istio-control/istio-discovery/templates/deployment.yaml

This fixes the istio/istio tests

Turn of Struct marshalling

---

gateways/istio-egress/templates/autoscale.yaml
gateways/istio-ingress/templates/autoscale.yaml

Fix the mistaken scale target reference in gateways hpa.

fix error scale target reference in gateways hpa.

---

istio-telemetry/mixer-telemetry/templates/deployment.yaml

Merge https://github.com/istio/istio/pull/16204

add priority class for telemetry.

---

istio-telemetry/grafana/dashboards/citadel-dashboard.json
istio-telemetry/grafana/dashboards/galley-dashboard.json
istio-telemetry/grafana/dashboards/istio-performance-dashboard.json
istio-telemetry/grafana/dashboards/mixer-dashboard.json
istio-telemetry/grafana/dashboards/pilot-dashboard.json

This PR is to make sure that the changes to the grafana dashboard in istio/istio have been fully ported over to the new installer (istio/installer).
TODO:
I will update the test here asap.

Update grafana-dashboard for syncing with istio/istio install k8s

---

istio-telemetry/tracing/values.yaml
kustomize/citadel/citadel.yaml
kustomize/default/gen-istio-autoinject.yaml
kustomize/default/gen-istio-citadel.yaml
kustomize/default/gen-istio-config.yaml
kustomize/default/gen-istio-discovery.yaml
kustomize/default/gen-istio-grafana.yaml
kustomize/default/gen-istio-ingress.yaml
kustomize/default/gen-istio-prometheus.yaml
kustomize/default/gen-istio-telemetry.yaml
kustomize/istio-canary/gen-discovery.yaml
kustomize/minimal/gen-discovery.yaml
security/citadel/templates/clusterrole.yaml
test/demo/gen-citadel.yaml
test/demo/gen-grafana.yaml
test/demo/gen-tracing.yaml

Fix two minor things:
* Citadel needs permissions for ns
* Tracing typo in image name
Everything else in this PR is just junk from run the targets to regen
config

Fix Citadel clusterrole and tracing image

---

gateways/istio-ingress/templates/role.yaml
istio-telemetry/prometheus-operator/templates/prometheus.yaml
kustomize/citadel/citadel.yaml
kustomize/default/gen-istio-citadel.yaml
kustomize/istio-1.2/default/istio.yaml
security/citadel/templates/clusterrole.yaml
security/citadel/templates/clusterrolebinding.yaml
test/demo/gen-citadel.yaml
test/istio-system-1.0.6.yaml

relevant with https://github.com/istio/istio/pull/16268

update rbac api version to v1.
