istio-control/istio-discovery/templates/configmap-envoy.yaml

Fixes the problem discussed in: https://github.com/istio-ecosystem/istio-installer/pull/2#discussion_r264734543
After debugging with tcpdump we saw that there are DNS queries for `istio-galley.istio-ingress.svc.cluster.local` et al. issued in the pilot pod. We fixed this in the configuration of envoy by appending the namespace variable.

Fix domainname of galley in envoy configmap istio-control/istio-discovery

---

istio-control/istio-discovery/templates/configmap.yaml
istio-control/istio-discovery/templates/deployment.yaml

The `--mcpServerAddrs` flag was deprecated for a while now and removed from master this morning (https://github.com/istio/istio/commit/612c138738446644d0db747604353e83f441e166).
In order for the installer to work with master, the value should be provided via the meshConfig.
This is also compatible with istio-1.1.

Move MCP-address to mesh config (instead of using flag).

---

Makefile

I have all my Istio stuff in `~/go/src/istio.io/...` not under a github.com folder. A quick grep of the Istio repo makes me think this is the standard. I suspect @costinm or others who made this have it in the github.com folder?
Also recommended in https://github.com/istio/istio/wiki/Dev-Guide
We need to either change this to match this, or we could try to make it smart

Fix istio repo location

---

.concourse/concourse.yaml
.concourse/set-pipeline.sh

Instead of calling `fly` with an environment variable that contains the KUBECONFIG, we now upload it to a credential manager and template it from there.
Co-authored-by: Ralf Pannemans <ralf.pannemans@sap.com>
Signed-off-by: Jakob Schmid <jakob.schmid@sap.com>

Use credential-manager for KUBECONFIG.

---

bin/iop

Co-authored-by: Ralf Pannemans <ralf.pannemans@sap.com>
This enables installing a istio-control  instance into a different namespace again, because the `--set global.configNamespace` flag (and other flags) had been discarded.

Add missing iop arguments to helm template again.

---

.concourse/concourse.yaml
bin/install.sh
bin/test.sh

We switch istio-env to the new istio-control, first delete the old istio-control namespace before restarting pods. This prevents pods from using the old istio-control without us noticing.
Co-authored-by: Ralf Pannemans <ralf.pannemans@sap.com>

Delete old ns BEFORE restarting pods.

---

global.yaml

Since this is an 'a-la-carte' installer, we need to default to permissive mode, since 
components and features will be added by user.
With isolation and Sidecar - we should strongly recommend that users explicitly set
policy, rules, etc at namespace level instead of a global default.

Mtls default to permissive

---

.drone.yml
Makefile
README.md
bin/install.sh
crds/crd-10.yaml
crds/crd-11.yaml
crds/crd-12.yaml
crds/crd-certmanager-10.yaml
crds/crd-certmanager-11.yaml

Some operators have complained that we install all CRDs as one blob
rather than permit the installation of Istio CRDs separately from
certmanager's CRDs.  The istio/istio repo has a solution for this.
Move that solution here.
Signed-off-by: Steven Dake <steven.dake@netapp.com>

Move around CRDs to handle certmanager

---

Makefile

- Set GOPATH only GOPATH is not set in the environment
- Change namespace for `Policy` and `Sidecar` to `bookinfo-demo`

Tiny change in Makefile

---

istio-policy/templates/config.yaml
istio-policy/values.yaml
istio-telemetry/mixer-telemetry/templates/config.yaml
istio-telemetry/mixer-telemetry/values.yaml

There were a large number of diffs around mixer config in the `mixer-telemetry` and `istio-policy` directories. This PR attempts to correct those issues.
In particular, this PR:
- updates the attribute manifests to match 1.1.x
- removes telemetry-related config from policy
- updates CRs to use the new-style config (only instances, handlers, rules)
- adds adapter config guards based on install options.
Helps to address #67.

fix: update mixer config to match istio/istio

---

istio-telemetry/mixer-telemetry/templates/config.yaml

Missed a few bits in #70 ; this corrects those issues.

fix(mixer-telemetry): remove bad template refs

---

bin/cleanup.sh
bin/test.sh

This makes the concourse pipeline more predictable as `install.sh` decides which namespace to use for `istio-control` based on `istio-env` labels of other namespaces (first in list).

cleanup.sh: remove istio-env label from all namespaces

---

.concourse/concourse.yaml
bin/test.sh

For testing purposes, the pipeline was set to a branch meaning that the status was not the actual status of master.

Set pipeline to master

---

istio-control/istio-autoinject/files/injection-template.yaml

The only field it references is one that is not configurable anyways, so
we can hard code it in the template safely. If it does need to be
configured in the future, we should read from values directly rather
than MeshConfig.
Part of https://github.com/istio-ecosystem/istio-installer/issues/75

Remove Injector dependency on MeshConfig

---

istio-telemetry/prometheus/templates/configmap.yaml

The port name in the service config for `istio-policy` was changed from `http-monitoring` to `http-policy-monitoring`. This PR updates the prom scrape config to match that change and allow the self-monitoring metrics from `istio-policy` endpoints to continue to be collected.
If the change of service port names was not intentional, or is not desired, we should change the value there instead.

fix(prometheus): adjust port name in scrape config

---

bin/test.sh

To fix the Make run-bookinfo target failure, update the INGRESS_HOST and INGRESS_PORT to use node port values when external load balancer is not avaialble.

Fix INGRESS HOST and PORT for local cluster

---

.circleci/config.yml
Makefile

Minikube install doesn't get right environment variables because it is
calling the script directly, causing failures.
Signed-off-by: John Howard <howardjohn@google.com>

Fix minikube install to use Make

---

gateways/istio-egress/templates/deployment.yaml
gateways/istio-ingress/templates/deployment.yaml
istio-control/istio-discovery/templates/configmap.yaml

Follow up PR for https://github.com/istio/installer/pull/83 to update tracing namespace.
Tracing component(zipkin or jaeger), if deployed, should be by default located in istioTelemetry namespace.

update tracing namespace.

---

istio-telemetry/prometheus-operator/Chart.yaml
istio-telemetry/prometheus-operator/templates/_affinity.tpl
istio-telemetry/prometheus-operator/templates/prometheus.yaml
istio-telemetry/prometheus-operator/templates/servicemonitors.yaml
istio-telemetry/prometheus-operator/values.yaml
test/install.mk
test/tests.mk

This PR is an attempt to add support for generating Prometheus Operator config to Istio. It is a port of https://github.com/istio/istio/pull/13407.
This PR assumes that the Prometheus Operator itself has been previously installed (example: `kubectl -n prom-operator apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/master/bundle.yaml`).
Motivations (Code Mauve):
- https://github.com/istio/istio/issues/10134
- https://github.com/istio/istio/issues/7528
- https://github.com/istio/istio/issues/5673
- https://github.com/istio/istio/issues/12915
- https://discuss.istio.io/t/istio-prometheus-to-scrape-metrics-from-service-specific-metrics-endpoint/926
- https://discuss.istio.io/t/how-to-update-prometheus-config/935
- …

feat: add support for prometheus operator config

---

test/docker/Dockerfile

else it would complain on my machine.
```
Step 3/24 : RUN go get -u sigs.k8s.io/kind  // Use latest since there is not a specific release to match the current kindest/node:v1.14.1 image
---> Running in e461839b2a88
package /: /: invalid import path: malformed import path "/": trailing slash
package Use: unrecognized import path "Use" (import path does not begin with hostname)
package latest: unrecognized import path "latest" (import path does not begin with hostname)
package since: unrecognized import path "since" (import path does not begin with hostname)
package there: unrecognized import path "there" (import path does not begin with hostname)
package is: unrecognized import path "is" (import path does not begin with hostname)
package not: unrecognized import path "not" (import path …
```

use the correct comment to get good docker build

---

Makefile
test/tests.mk

Run in parallel, skip tests that require custom setup.
Close to being able to run all of them (not just the small presubmit
subset).

Improve integration tests

---

istio-control/istio-autoinject/templates/deployment.yaml
istio-control/istio-autoinject/templates/mutatingwebhook.yaml
istio-control/istio-autoinject/values.yaml

Introduces a 'sidecarInjectorWebhook.selfSigned' option to the 'istio-autoinject'
component that allows to generate a self-signed CA and issue a long-lived
certificate during template rendering that can be used to authorize a webhook
workload.

Add an option to use a self-signed cert for autoinject webhook

---

bin/test.sh

- Extend default test timeout from 3m to 5m

Updates to get `make test` to work

---

Makefile

`kind` in master is broken, see: https://github.com/kubernetes-sigs/kind/issues/509, use released version as a workaround.

fix kind issue in CI.

---

test/buildkite/Dockerfile
test/docker/Dockerfile

Kind was updated to use Go modules which requires Go 1.12.5 and modules turned on.
We will keep using the `edge` version.

Update kind in images to latest edge - requires Go 1.12.5 and modules

---

gateways/istio-egress/templates/poddisruptionbudget.yaml
gateways/istio-ingress/templates/_podDisruptionBudget.tpl
gateways/istio-ingress/templates/poddisruptionbudget.yaml
istio-control/istio-discovery/templates/poddisruptionbudget.yaml
istio-policy/templates/poddisruptionbudget.yaml
istio-telemetry/mixer-telemetry/templates/poddisruptionbudget.yaml
test/noauth.mk

IIRC, we have a limitation about the `PodDisruptionBudget `, see: https://github.com/istio/istio/issues/11210
@linsun @sdake We still can need the immutable pdb with `kubectl apply...`, right?

make pdb immutable.

---

test/tests.mk

Tracing test has been added in main repo: https://github.com/istio/istio/pull/13790, the new installer hasn't imported tracing component, we need to temporarily exclude that.

exclude tracing test.

---

test/install.mk
test/tests.mk

When running a full `make test`, all namespaces are selected for auto-injection, which causes issues with the prom operator install. This PR moves the prom operator to its own namespace and disables auto-injection in that namespace.

fix: ensure prom operator is not installed in an auto-inject namespace

---

gateways/istio-ingress/templates/deployment.yaml
istio-telemetry/mixer-telemetry/templates/deployment.yaml
kustomize/citadel/citadel.yaml
kustomize/istio-ingress/istio-ingress.yaml
security/citadel/templates/deployment.yaml
test/demo/istio-testing/k8s.yaml
test/demo/k8s.yaml
test/istio-system-1.0.6.yaml

Context: https://github.com/istio/istio/issues/12650
The annotation `scheduler.alpha.kubernetes.io/critical-pod` is deprecated k8s 1.13 and will be removed in 1.14, let's remove critical pod annotation.
See: https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/#marking-pod-as-critical

remove to be deprecated critical pod annotation.

---

Makefile

The order of parameters to `docker run` was wrong. As a result, bash tried to execute the file `GOPATH=${GOPATH}` instead of forwarding the environment variable into the container.
```bash
$ make build
docker run -it --rm -v /Users/istio/go:/Users/istio/go --entrypoint /bin/bash istionightly/kind:v1.14.1-1 \
-e GOPATH=/Users/istio/go \
-c "cd /Users/istio/go/src/istio.io/installer; ls; make run-build"
/bin/bash: GOPATH=/Users/istio/go: No such file or directory
make: *** [build] Error 1
```

fix error in make target "build"

---

istio-control/istio-autoinject/templates/sidecar-injector-configmap.yaml
istio-control/istio-autoinject/values.yaml

Capability to specify alwaysInjectSelector and neverInjectSelector in the Helm chart.
Resolves istio/istio#14020

Add neverInjectSelector and alwaysInjectSelector properties to Helm chart

---

istio-telemetry/grafana/dashboards/istio-service-dashboard.json
istio-telemetry/grafana/dashboards/istio-workload-dashboard.json

Use `irate` in the denominator to match use in numerator in the service and workload dashboards.
Fixes: https://github.com/istio/istio/issues/13626

fix(dashboards): ensure irate used for success rate calc

---

global.yaml

A part of https://github.com/istio/istio/issues/13710
5m default was discussed in the networking WG

Modify dns refresh rate to 5m

---

istio-telemetry/mixer-telemetry/templates/service.yaml

This is needed for prometheus to scrape it properly.

Add label to telemetry service

---

test/tests.mk

We should be aware that this test is failing in a way that is a real issue and will affect users -- `istioctl version` is broken with the different namespaces.
However if we have a test that is always red we mask other issues so may be best to turn it off

Exclude istioctl test

---

test/tests.mk

See: https://github.com/coreos/prometheus-operator/blob/master/Documentation/design.md#prometheus
> For each Prometheus resource, the Operator deploys a properly configured StatefulSet in the same namespace. The Prometheus Pods are configured to mount a Secret called <prometheus-name> containing the configuration for Prometheus.
We should check the promesheus **statefulset**, instead of **deployment**, as prometheus-operator will create **statefulset** for each `Prometheus` resource, not **deployment**.

verify statefulset for prometheus-operator test 

---

istio-telemetry/grafana/dashboards/istio-performance-dashboard.json
istio-telemetry/grafana/dashboards/pilot-dashboard.json
istio-telemetry/grafana/values.yaml

https://github.com/istio/istio/pull/14174 suggested a useful set of panels for monitoring Pilot that included a "push" panel and a condensed "pilot errors" panel. This PR adds the suggested row to the pilot dashboard.
Reviewers: please try deploying this in your own clusters for validation.
Snapshot: https://snapshot.raintank.io/dashboard/snapshot/gvJIfR64GZ4T2ARIbdH16KRQBcK4ws4t
Note: It appears I accidentally branched from https://github.com/istio/installer/pull/183. So, I can move this commit around if that PR proves troublesome, but I wanted to get this under review ASAP.

Add Pilot Pushes row to pilot dashboard

---

istio-telemetry/grafana/dashboards/istio-performance-dashboard.json
istio-telemetry/grafana/values.yaml

This PR accomplishes the following:
- updates the default image of grafana to the latest release (6.0.2 -> 6.1.6).
- updates the performance dashboard by:
- repairing the broken panels that had gone missing
- converting to consistent use of rows
- moving the README to a collapsed-by-default panel at the top
- adding perf-relevant panels for individual components to the bottom (as inspired by @Stono).
- **converts the places where `istio-system` was hardcoded to use `istio-control` as the namespace.** This will make the perf dashboards work for traditional installs, but may cause different results when components are deployed in distinct namespaces.
- **converts the workload names from `istio-ingressgateway` to `ingressgateway`**. This may mean additional work is required to back-port to …

fix(dashboards): update grafana and repair broken performance dash

---

istio-control/istio-discovery/templates/configmap.yaml

Adds support of configuring 'locality-aware load balancing' via the `values.yaml`.

Forward-port a missing feature from the old installer

---

.mergify.yml

Merging is blocked because we have it require a test we no longer have.

Fix mergify required tests

---

istio-cni/values_gke.yaml

Followup PR for https://github.com/istio/installer/pull/195, all values for istio-cni are supposed to be under `cni` parent.

fix values structure for istio-cni.

---

gateways/istio-egress/templates/deployment.yaml
gateways/istio-ingress/templates/deployment.yaml

for a gateway pod-annotations must also be set in the env.

Add ability to send annotations as env vars automagically

---

istio-telemetry/prometheus/templates/configmap.yaml
kustomize/istio-telemetry/istio-grafana.yaml
kustomize/istio-telemetry/istio-prometheus.yaml
test/demo/k8s.yaml

We control the metrics that are emitted at the proxy.
This configuration is no longer needed.

Remove prometheus metric_relabel_configs

---

test/tests.mk

The echo tests were removed in favor of the reachability tests

Echo test -> reachability test

---

bin/install.sh

match [name](https://github.com/istio/installer/blob/master/gateways/istio-ingress/templates/deployment.yaml#L5)
```
+ kubectl rollout status deployment ingressgateway -n istio-ingress --timeout=5m
Error from server (NotFound): deployments.extensions "ingressgateway" not found
```

fix ingress deployment name

---

kustomize/istio-telemetry/mixer-telemetry.yaml

Was merged before auto backport was merged

backport to 1.2: fix configNamespace for telemetry (#201)

---

security/certmanager/templates/poddisruptionbudget.yaml

Since the replicas of cert-manager is configurable  after https://github.com/istio/installer/pull/210, we need to reverts istio/installer#220 to add back PDB for cert-manager.

Revert "remove pdb for cert-manager."

---

.concourse/concourse.yaml
bin/install.sh

The install of 1.1 is not supported, so I have adjusted the pipeline to
* install daily-master
* test
* install old (fixed) version of master #until 1.2 was released
* test
* update to daily master
* test

Use daily master for installer pipeline instead of 1.1

---

istio-control/istio-autoinject/templates/clusterrole.yaml

@sdake 
Tested this manually for-
1. go templating
2. functionality by verifying in our test cluster that auto injection of sidecar works with the updated role

Make sidecar injector clusterrole more restrictive by specifying resourcenames

---

test/tests.mk

fix the issue about
```
--- FAIL: TestCitadelBootstrapKubernetes (10.67s)
bootstrap_writesecret_test.go:65: Failed to retrieve Citadel CA-root secret.
```
for the new installer, the citadel is in `istio-system` ns instead of `istio-control`

use istio-system for istioNamespace and systemNamespace

---

istio-control/istio-config/templates/validatingwebhookconfiguration.yaml.tpl
test/tests.mk

The installer code changes cannot pass the ci due to https://github.com/istio/istio/pull/14680. remove the `presubmit` in this repo accordingly.

Remove presubmit label

---

istio-control/istio-discovery/templates/configmap.yaml

Protect the SDS config fields by helm flag global.sds.enabled (https://github.com/istio/istio/pull/15109), and keep the SDS config consistent with istio/install/kubernetes/helm/istio/templates/configmap.yaml

Update SDS in config map

---

security/citadel/templates/clusterrole.yaml

cannot create configmap `istio-citadel` without proper permission.

Update the clusterrole for citadel

---

istio-telemetry/tracing/values.yaml

There has some problems I think
1. The image is from docker hub.
if we use the version `2`,  it may lead our tested version is not same as released version. for example: when we did test for 2.14.1 and client may use 2.14.2 for their environment.
2. we have another PR to ensure the `imagePullPolicy` is `IfNotPresent`. after that, the latest or our desired image cannot be applied to client's environment if there is an old version `2` exists.
FYI @morvencao 

Use strict version for zipkin

---

.circleci/config.yml

Currently the test framework can either always set the namespace label
or never set it. We need to make it smarter then we can turn this back
on.

Turn on namespaces by default

---

bin/testEnvRootMinikube.sh

There are some issues logged in minikube community about pod cannot direct traffic to itself via a service. refer to:
https://github.com/kubernetes/minikube/issues/1568
https://github.com/kubernetes/kubernetes/issues/20475
Propose to apply this workaround method to fix - `
ci/circleci: install-minikube — Your tests failed on CircleCI `

Fixed: pod cannot direct traffic to itself via a service

---

gateways/istio-egress/templates/deployment.yaml
gateways/istio-ingress/templates/deployment.yaml
global.yaml
istio-control/istio-autoinject/files/injection-template.yaml
istio-control/istio-autoinject/templates/deployment.yaml
istio-control/istio-config/templates/deployment.yaml
istio-control/istio-discovery/templates/deployment.yaml
istio-policy/templates/deployment.yaml
istio-telemetry/mixer-telemetry/templates/deployment.yaml
kustomize/istio-control/istio-autoinject.yaml
security/citadel/templates/deployment.yaml
security/nodeagent/templates/daemonset.yaml

Currently there is no option in helm charts to output Istio components logs in JSON format. By default all the component logs are in TEXT format.
Each istio component container have option to change output as JSON using --log_as_json argument but in helm charts there is no way to add this argument
--log_as_json | Whether to format output as JSON or in plain console-friendly format
Added global variable called logAsJson in global.yaml and updated helm charts to use --log_as_json container argument
For reference:
This PR was raised before and tested https://github.com/istio/istio/pull/13678

Added --log_as_json container arg to all istio components

---

istio-control/istio-config/templates/clusterrole.yaml
kustomize/istio-control/istio-config.yaml

Fixes:
2019-07-08T21:43:47.844776Z     error   pkg/mod/k8s.io/client-go@v10.0.0+incompatible/tools/cache/reflector.go:95: Failed to list *v1.Namespace: namespaces is forbidden: User "system:serviceaccount:istio-control:istio-galley-service-account" cannot list resource "namespaces"
in API group "" at the cluster scope

Add missing namespaces permissions for Galley

---

crds/templates/crds.yaml

Sync the cert-manager crds changes from istio-operator https://github.com/istio/operator/pull/69
Although the CI for new installer apply all crds with `kubectl`, it's necessary add crds for cert-manager in chart template, because the istio-operator renders all the CRDs with crds chart.

fix missing crds for certmanager.

---

istio-telemetry/tracing/templates/deployment-opencensus.yaml
istio-telemetry/tracing/templates/service.yaml
istio-telemetry/tracing/values.yaml

This PR adds a third option for the application backing the `zipkin` service for Istio: the [OpenCensus Service](https://opencensus.io/service/) (with a `zipkin` receiver).
In this PR, we deploy the [collector](https://opencensus.io/service/components/collector/), configured with a [receiver](https://opencensus.io/service/receivers/) for `zipkin`. At the moment, the sole [exporter](https://opencensus.io/service/exporters/) configuration supported is `stackdriver`. However, that section can be extended.
Notably, the OC service does not expose a UI, so if the provider is set to `opencensus` the artifact for the tracing UI service is not generated.

feat(tracing): add alpha support for opencensus service

---

security/citadel/templates/deployment.yaml
test/demo/k8s.yaml
test/demo/kustomization.yaml
test/demo/namespace.yaml
test/demo/values.yaml
test/install.mk

Currently the demo will generate config for all components but then
reference this pregenerated config for citadel. This changes it to align
with other components and be self contained.
Ran make run-build-demo which is where most changes here come from

Make demo directly install citadel

---

istio-telemetry/kiali/templates/clusterrole.yaml

Add the missed sidecars in kiali clusterrole.yaml file.

Add sidecars for kiali

---

.circleci/config.yml
Makefile
test/install.mk
test/tests.mk

in this PR https://github.com/istio/istio/pull/15284, we enable get `enableNamespacesByDefault` from command line. pass this value in the new installer to enable test with `enableNamespacesByDefault` is false

Pass enableNamespacesByDefault to istio config

---

gateways/istio-ingress/templates/rolebindings.yaml

kubectl apply --prune -l release=<release name> is unable to create rolebinding for ingress-gateway. This PR fixes the issue by adding a release label to the rolebinding. 
Signed-off-by: Jon Yucel <jon.yucel@getcruise.com>

fix ingress-gateway rolebinding labels

---

istio-telemetry/prometheus-operator/templates/servicemonitors.yaml
istio-telemetry/prometheus-operator/values.yaml
istio-telemetry/prometheus/templates/configmap.yaml
istio-telemetry/prometheus/values.yaml

When prometheus.secure is set to false, prometheus deployment will not mount from the istio.default secret. However, it will still try to scrap from the `kubernetes-pods-istio-secure` endpoint that requires the certificate mounted from istio.default secret, resulting in unnecessary error messages in prometheus pods. This disables the scrap endpoint when prometheus.security=false

disable scrap endpoints that require certificate when prometheus.security=false

---

istio-telemetry/prometheus-operator/templates/servicemonitors.yaml

Incorrectly named `prometheus.security.enabled` to `prometheus-operator.security.enabled`.

fix wrong helm variable name

---

istio-control/istio-discovery/templates/configmap.yaml
istio-control/istio-discovery/values.yaml
istio-telemetry/mixer-telemetry/templates/deployment.yaml
istio-telemetry/mixer-telemetry/values.yaml

This PR addresses 2 issues:
- Mixer is currently hard coded to run with a sidecar. This should be controllable similarly to Pilot.
- Mixer is current using `global.useMCP`, but Pilot is using `pilot.useMCP`. We should be consistent, so I introduced a `mixer.telemetry.useMCP`.

Mixer should use local useMCP var and Mixer's sidecar should be configurable

---

istio-telemetry/mixer-telemetry/values.yaml

Fix broken `nodeSelector` and `tolerations` for mixer telemetry.

fix telemetry values.

---

istio-policy/templates/deployment.yaml
istio-telemetry/mixer-telemetry/templates/deployment.yaml

#299 introduced another regression, and now telemetry metrics are no longer received for insecure control planes. 
I'm not sure if this is the right way to fix this issue, but at least it's an attempt parallel to what was intended with #299.
In addition to the fix, this PR also copies the istio-telemetry changes into istio-policy to make them consistent.

Telemetry is broken when controlPlaneSecurity is disabled

---

istio-cni/templates/daemonset.yaml

Fixing a small typo in the istio-cni Helm template.

Typo in istio-cni daemonset template

---

istiocoredns/Chart.yaml
istiocoredns/templates/configmap.yaml
istiocoredns/templates/deployment.yaml
istiocoredns/values.yaml

This PR updates the CoreDNS version to a more recent one and makes it compatible with CoreDNS versions above 1.3.2 (see: https://github.com/istio/istio/pull/16417).

Update CoreDNS version to a more recent one

---

README.md
gateways/istio-egress/templates/deployment.yaml
gateways/istio-ingress/templates/deployment.yaml
istio-control/istio-autoinject/templates/configmap.yaml

pilot is installed in global.configNamespace instead of global.istioNamespace

Use configNamespace for pilot instead of istioNamespace

---

istio-telemetry/mixer-telemetry/templates/stackdriver.yaml
istio-telemetry/mixer-telemetry/values.yaml

Example command to use the newly added values: `helm template istio-telemetry/mixer-telemetry -x templates/stackdriver.yaml --name istio --namespace istio-system --values global.yaml --set mixer.adapters.stackdriver.enabled=true --set mixer.adapters.stackdriver.contextGraph.enabled=true --set global.meshID=\<mesh_uid\>`
mesh_uid label will just be empty string if not set. cc @elfinhe @djazayeri please take a look, thanks!

Add context graph and mesh uid into stackdriver template

---

global.yaml

allow long protocol detection timeout for test
